apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sctp-loader
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: sctp-loader
  template:
    metadata:
      labels:
        app: sctp-loader
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: sctp-loader
          image: registry.access.redhat.com/ubi8/ubi-minimal
          command:
            - /bin/bash
            - -c
            - |
              chroot /host modprobe sctp
              echo "SCTP module loaded"
              sleep infinity
          securityContext:
            privileged: true
          volumeMounts:
            - name: host
              mountPath: /host
      volumes:
        - name: host
          hostPath:
            path: /
